CREATE DATABASE PRUEBAS;

USE PRUEBAS;

CREATE TABLE PRODUCTOS (
	ID_PRODUCTO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(40),
    PRECIO DECIMAL(16,2)
);

CREATE TABLE VENTAS (
	ID_VENTA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

INSERT INTO PRODUCTOS (NOMBRE, PRECIO)
VALUES ('LAPTOP', 3000),
		('PC', 4000),
        ('MOUSE', 100),
        ('TECLADO', 150),
        ('MONITOR', 2000),
        ('MICROFONO', 350),
        ('AUDIFONOS', 450);
        
SELECT * FROM PRODUCTOS;

INSERT INTO VENTAS (ID_PRODUCTO, CANTIDAD)
VALUES (5, 8),
		(1, 15),
        (6, 13),
        (6, 4),
        (2, 3),
        (5, 1), 
        (4, 5),
        (2, 5), 
        (6, 2),
        (1, 8);
        
SELECT * FROM VENTAS;

-- 1.5) Traer todos los productos que tengan una venta
SELECT PRO.NOMBRE, COUNT(VEN.CANTIDAD) AS TOTAL FROM PRODUCTOS AS PRO
JOIN VENTAS AS VEN ON PRO.ID_PRODUCTO = VEN.ID_PRODUCTO
GROUP BY PRO.NOMBRE HAVING COUNT(VEN.ID_VENTA) = 1;

-- 1.6) Traer todos los productos que tengan ventas y la cantidad total de productos vendidos
SELECT PRO.NOMBRE, SUM(VEN.CANTIDAD) AS TOTAL FROM PRODUCTOS AS PRO 
JOIN VENTAS AS VEN ON PRO.ID_PRODUCTO = VEN.ID_PRODUCTO
GROUP BY PRO.NOMBRE;

-- 1.7) Traer todos los productos y la suma total vendida por producto
SELECT PRO.NOMBRE, SUM(PRO.PRECIO*VEN.CANTIDAD) AS TOTAL FROM PRODUCTOS AS PRO
FULL OUTER JOIN VENTAS AS VEN ON PRO.ID_PRODUCTO = VEN.ID_PRODUCTO
GROUP BY ID_PRODUCTO;

-- FULL OUTER JOIN no es soportado por MySQL de forma nativa, se debe hacer un UNION entre LEFT Y RIGHT
SELECT PRO.NOMBRE, SUM(PRO.PRECIO * VEN.CANTIDAD) AS TOTAL
FROM PRODUCTOS AS PRO
LEFT JOIN VENTAS AS VEN ON PRO.ID_PRODUCTO = VEN.ID_PRODUCTO
GROUP BY PRO.NOMBRE

UNION

SELECT PRO.NOMBRE, SUM(PRO.PRECIO * VEN.CANTIDAD) AS TOTAL
FROM PRODUCTOS AS PRO
RIGHT JOIN VENTAS AS VEN ON PRO.ID_PRODUCTO = VEN.ID_PRODUCTO
GROUP BY PRO.NOMBRE;
